project:
  type: book
  output-dir: docs
  resources:
    - .nojekyll

book:
  title: "<span style='font-weight: 700'>Sampling</span><br/><i style='color: #00b7ff'>Strategies</i>"
  subtitle: "Survey Design and Parameter Estimation"
  author: "Andrés Gutiérrez"
  search: true
  page-navigation: true
  sidebar:
    style: floating
    collapse-level: 1
  date: today
  date-format: long
  chapters:
    - index.qmd
    - chapters/frontmatter.qmd
    - chapters/cap1.qmd
    - chapters/cap2.qmd
    - chapters/cap3.qmd
    - chapters/cap4.qmd
    - chapters/cap5.qmd
    - chapters/cap6.qmd
    - chapters/cap7.qmd
    - chapters/cap8.qmd
    - chapters/cap9.qmd
    - chapters/cap10.qmd
    - chapters/cap11.qmd
    - chapters/cap12.qmd
    - chapters/cap13.qmd
    - chapters/cap14.qmd
    - chapters/cap15.qmd
  page-footer: "Sampling Strategies: Sampling Design and Parameter Estimation"

bibliography: references.bib
lang: en

crossref:
  chapters: true
  eq-prefix: equation
  fig-prefix: figure
  tbl-prefix: table

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: scripts/number-callouts.html
    toc: true
    toc-depth: 3
    toc-location: right
    smooth-scroll: true
    number-sections: true
    code-fold: false

execute:
  echo: true
  warning: false
  message: false
  freeze: auto
