# Prólogo {-}

El muestreo es tal vez el oficio que caracteriza mejor la disciplina estadística. Se trata nada menos que de la planeación y ejecución de la recolección organizada de información con el fin de conocer o estimar propiedades generales de una población o de un fenómeno natural. Para ello, involucra, no solo la estrategia de selección probabilística de una muestra, sino que también hace explícito el estimador que proveerá el valor del parámetro que, a juicio del investigador, resume la propiedad estudiada.

Es indudable que los sistemas de cómputo han contribuido enormemente al desarrollo de nuevos métodos y a la práctica de los tradicionales con mayor confianza. Las fórmulas y los algoritmos se programan y se ponen en marcha y todo el trabajo numérico se deja en manos del computador, incluyendo la generación de los números pseudoaleatorios como punto de partida para la selección de las muestras y para la exploración de propiedades de los diseños mediante métodos de simulación. Igualmente, el muestreo se ha beneficiado de desarrollos abundantes y profundos de otros campos de la estadística que lo han enriquecido con nuevos métodos en los años recientes.

El profesor Andrés Gutiérrez emprende la tarea de entregar al lector un libro conceptualmente sólido, que se caracteriza por el equilibrio en la presentación intuitiva de los conceptos, apoyándose en (1) su estrategia pedagógica de Marco y Lucy, manteniendo una población y un marco de muestreo a lo largo de su texto, lo que le permite ejemplificar y comparar los diseños en lo referente a su eficiencia, (2) el desarrollo matemático riguroso de las propiedades de los diseños y de los estimadores, y (3) la práctica de los algoritmos con el paquete TeachingSampling, elaborado por él mismo para ilustrar los procedimientos propuestos.

De esta manera, el estudioso del tema encuentra cómo aplicar de manera inmediata los diversos procedimientos sin verse en la necesidad de emprender manualmente la búsqueda de soluciones o, si lo desea, tiene a su alcance los programas que le permiten comparar los resultados obtenidos con los que encuentra por sus propios medios. La primera parte contiene los métodos tradicionales que usualmente se enseñan en un primer curso de muestreo. La segunda está diseñada para un curso más avanzado de pregrado. En la tercera, el autor incluye temas recientes, provenientes de artículos publicados en revistas especializadas y de aparición más escasa en otros textos y que pueden ser parte de cursos de posgrado.

La lectura del texto es agradable y clara, acompañada de numerosos ejemplos lexicográficos con cantidades pequeñas de datos que ilustran el detalle de las posibilidades. Sin duda, el libro que nos presenta el profesor Andrés Gutiérrez tiene el sello de un trabajo personal serio y novedoso que el lector apreciará.

::: {.text-end}
Jorge Ortiz Pinilla, PhD.  
Diplôme de docteur de troisième cycle  
Université Henri Poincaré, Nancy 1
:::


# Prefacio {-}

Aunque muy poderoso, el término estrategia de muestreo no ha tenido la trascendencia pertinente en el mundo del muestreo. Se habla de la eficiencia, precisión e incluso insesgamiento de un estimador sin tener en cuenta que tales propiedades están ligadas al diseño de muestreo que se haya utilizado en la recolección de la información. Para el autor, el aprendizaje de esta materia es más sencillo cuando se valora de igual manera el diseño de muestreo junto con el estimador del parámetro de interés utilizado en la población finita. No se puede desconocer la regla de oro del muestreo que clama: utilizar diseños de muestreo que induzcan probabilidades de inclusión (o selección, según sea el caso) proporcionales al valor de la característica de interés en la población y utilizar estimadores que involucren dichas probabilidades. Por lo anterior, se ha decido titular este texto como *Estrategias de muestreo, diseño de encuestas y estimación de parámetros.*

En la búsqueda combinada de una mejor estrategia de muestreo se ha querido dividir este texto en tres partes que pueden ser utilizadas en los distintos niveles de pregrado así como en cursos de posgrado, dependiendo de la dificultad del tema. La división del libro corresponde al desarrollo teórico del muestreo a través de su corta historia.

La primera parte del libro es un recuento de las estrategias de muestreo más comúnmente utilizadas. Con una muy robusta rigurosidad estadística y matemática, el lector será introducido en el ámbito de la inferencia basada en el diseño de muestreo, que considera a los valores de la característica de interés como pseudoparámetros fijos y no como realizaciones de variables aleatorias. Este recorrido se hace más ameno al introducir a Marco y Lucy, compañeros inseparables en cada estrategia planteada, que corresponden a conjuntos de datos que se obtuvieron para la realización de una encuesta. Así, Marco es el pseudonombre del marco de muestreo y Lucy corresponde a una población de empresas en el sector industrial. A diferencia de la mayoría de los libros de muestreo clásicos, se ha querido proponer la revisión de todas las estrategias de muestreo con un sólo «marco» de muestreo, en algunas ocasiones más generoso que en otras, y una sola población, «Lucy», con el fin de plantear al lector un problema que puede ser resuelto desde diversos ángulos y no, como sucede en algunos libros de muestreo, proponer ejemplos resueltos en donde el lector no tiene la oportunidad de cuestionarse acerca del desarrollo de la estrategia. En esta parte se exponen tres conceptos totalmente determinantes al momento de plantear una estrategia de muestreo. El primero, y más importante de ellos, es el soporte que define la realización de una muestra probabilística y por consiguiente la validez en la inferencia. El lector puede darse cuenta de la importancia de este concepto al diferenciarlo de la muestra aleatoria, que no es más que un vector aleatorio. En segundo lugar se hace énfasis en el concepto de diseño de muestreo tratándolo como una distribución de probabilidad multivariante sobre el soporte. En la mayoría de estrategias planteadas en esta primera parte se demuestra que efectivamente el diseño de muestreo propuesto verifica las propiedades de una distribución de probabilidad. Por supuesto, el último concepto es el de estimador cuya definición y uso es más difundido entre los usuarios. Cada capítulo y cada sección adjunta un pequeño ejemplo léxico-gráfico y una aplicación de la estrategia propuesta con Marco y Lucy mediante el desarrollo computacional del paquete TeachingSampling [@Teaching], creado en el ambiente del software de uso libre R de la manera más amigable posible.

La segunda parte de este texto, corresponde a la utilización y aprovechamiento de la información auxiliar disponible en el marco de muestreo. No sólo se revisan estimadores que mejoran la eficiencia de la estrategia, sino que también se adjunta al proceso de estimación el uso de un modelo que permite *describir* el comportamiento de la característica de interés en la población dando un paso muy importante en el desarrollo de la inferencia al tratar, aunque de manera aislada, a la característica de interés como una variable aleatoria en el modelo propuesto. En esta parte, se sigue el hermoso enfoque de @Beth en donde no se hacen supuestos acerca de la validez del modelo de superpoblación. En esta línea de pensamiento la única aseveración que se realiza es que los residuales del modelo sí tienen una menor varianza que la característica de interés. Al final de esta parte se presenta una muy breve introducción a la inferencia en poblaciones finitas bajo un enfoque basado en el modelo supuesto. Es interesante observar que, con el pasar de los días, el uso de estas técnicas es más y más común, sobre todo en la estimación de dominios raros más conocidos como áreas pequeñas. Este apartado empieza con la famosa discusión de @Basu1971 que aun hoy sigue siendo la piedra de tropiezo entre las corrientes de la estadística. Este tipo de inferencia no considera el diseño de muestreo ni la forma en la que la información fue recolectada, sino que se basa en el modelo poblacional propuesto para realizar la inferencia. Sin embargo, cuando el modelo poblacional es errado también los serán las estimaciones.

La tercera parte, apta para un curso de posgrado, intenta acceder a los mayores avances metodológicos que, con el paso del tiempo, dejan de ser innovaciones para convertirse en técnicas obligatorias en la mejora de la eficiencia de la estrategia. Entre otros selectos temas, se consideran los estimadores de calibración, el muestreo balanceado y el muestreo indirecto. Estos contenidos están supeditados a un gran sesgo personal inducido por los años de asistencia al seminario de muestreo de la Universidad Nacional de Colombia.

Por supuesto, este libro no hubiera podido ser escrito sin la enorme influencia del maestro Leonardo Bautista, quien me enseñó que lo importante no es la memorización de fórmulas sino darles sentido y traerlas a la vida mediante el uso de la mejor estrategia. Lo anterior tiene sentido, no sólo en el desarrollo práctico de la ciencia estadística, sino en el diario vivir.

Por último, el autor expresa sus agradecimientos a Dios, quien le ha dado todo lo que tiene y le ha seleccionado para pertenecer en la muestra; de no ser así, no se habrían escrito estas líneas. Agradece el infinito apoyo que encontró en su esposa Hanwen Zhang en la corrección de las demostraciones así como en la invaluable motivación que le ha brindado desde el día que la conoció. De la misma manera, agradece enormemente el continuo ánimo de su tío y amigo Oscar Ortega, por sus valiosos consejos desde su juventud y porque gran parte de este material se gestó en su residencia de los Estados Unidos. A su padre por la excelente crianza, a su abuela Lola porque sus oraciones nunca han cesado y a sus tías Martha, Myriam, Pilar y Clara. A su hermanita Tatiana Torres. A sus valiosos amigos. 

